services:
  memos:
    image: neosmemo/memos:0.28
    container_name: memos
    restart: always
    volumes:
      - memos_data:/var/opt/memos
    environment:
      MEMOS_PORT: 5230
      MEMOS_DRIVER: postgres
      MEMOS_DSN_FILE: /run/secrets/memos_db_connection
      MEMOS_INSTANCE_URL: https://timeline.plaintext.stream
    secrets:
      - memos_db_connection
    networks:
      - websrv

networks:
  websrv:
    external: true

secrets:
  memos_db_connection:
    external: true

volumes:
  memos_data:

