services:
  acme-sh:
    image: neilpang/acme.sh
    container_name: acme-sh
    restart: always
    volumes:
      - acme-sh_cert:/cert
    environment:
      - CF_Token=${CF_Token}
    command: daemon

volumes:
  acme-sh_cert:

